### ISSUE TITLE
Turbo needs to be installed by hand to run optimisation examples?

### ISSUE THREAD

**Issue by mjw63** [DarkMachines/high-dimensional-sampling#38]
Hi,

I tried running the pyscannerbit example today (on a new Ubuntu 18.04 system), but I got a failure when it couldn't import TurboM. I ended up installing Turbo by hand using:

git clone https://github.com/uber-research/TuRBO
cd TuRBO
python setup.py sdist
pip3 install .

Should we add these instructions to the README? Also, is it good practise to require all algorithms to be present to run any of them? This might hold back users from testing their own technique.

Cheers,

Martin

**Comment by mjw63** [comment]
hmm- the plot thickens. After getting this working, I redid the pip3 install of high-dimensional samplinh to get Luc's new functions in place, but I get the turbo error again when I try to run. So I think the install is actually installing a turbo package that is not the right one. This is on Ubuntu 18.04.

**Comment by bstienen** [comment]
What is the error you get? I guess the problem you are having is the following (but it is always good to check the error message anyway): `turbo` is a [package written by Uber](https://github.com/uber-research/TuRBO), but also a [package for web development](https://pypi.org/project/turbo/). When installing the package through `pypi` the last one is installed. As far as I know (please correct me on this if I am wrong) the Uber package is not on pypi yet, making it not installable through `pip install` commands.

I agree with both your points: it should be in the README and we should not have a requirement to have all packages installed. I will update the code later today to fix this and alter the README accordingly. My suggestion would be to place the dependencies and their installation instructions on a Wiki page (making the README just a bit cleaner).

**Comment by mjw63** [comment]
I just uninstalled turbo using pip3 uninstall, which I did multiple times to remove anything called turbo. I then installed hds again, but I get this error:

Traceback (most recent call last):
  File "experiments/diver_plot.py", line 5, in <module>
    from high_dimensional_sampling import optimisation
  File "/home/mwhi/.local/lib/python3.6/site-packages/high_dimensional_sampling/optimisation/__init__.py", line 7, in <module>
    from .turbo import TuRBO  # noqa: F401
  File "/home/mwhi/.local/lib/python3.6/site-packages/high_dimensional_sampling/optimisation/turbo.py", line 3, in <module>
    from turbo import TurboM
ImportError: cannot import name 'TurboM'

So I can't shake the feeling that something is weird in the turbo installation that it does.

**Comment by bstienen** [comment]
Yeah, that is the error you get when the wrong `turbo` package is installed. Apparently the setup of the package does not install the right one... I think this is a bit weird, as I explicitly say to install

    turbo @ git+https://github.com/uber-research/TuRBO.git

Need to have a closer look at that, but be assured that it is not your fault here. @williamjameshandley, do you have a suggestion on how to fix it?

**Comment by bstienen** [comment]
@mjw63, when installing HDS, there should be some terminal output about the turbo package that is installed. Could you post that part of the terminal output here? Might help solving the issue.

**Comment by bstienen** [comment]
I have updated the package (#39). Can you check if it works now?

**Comment by mjw63** [comment]
yep, it now works - thanks!
