### ISSUE TITLE
Hidden function installation broken?

### ISSUE THREAD

**Issue by mjw63** [DarkMachines/high-dimensional-sampling#40]
Hi,

Working on a new Ubuntu 18.04 desktop, I just got a problem with the installation of the hidden functions. For some reason, the pip install put them here:

~/.local/lib/python3.6/site-packages/high_dimensional_sampling/hidden_functions/

instead of here:

~/.local/lib/python3.6/site-packages/high_dimensional_sampling/hidden_functions/18.04/

so that the function that checks the compiled version failed at runtime. Making the directory by hand and moving the test functions into it cured the problem.

This worked fine on my Ubuntu 18.04 laptop! So I'm not sure how we can debug this.

Cheers,

Martin

**Comment by mjw63** [comment]
hmm- I am now more confused. 

The functions that it put in ~/.local/lib/python3.6/site-packages/high_dimensional_sampling/hidden_functions/ do not give the same answers as the local functions in my highdimensionalsampling clone. At least this is true for test_func_1.bin that I just ran an optimisation on. 

Maybe this is a clue: is it using the old functions from before Luc added dimensionality?

**Comment by bstienen** [comment]
Which command do you use to install the package? It sounds weird to me that the package installs files that are not present in the package anymore. Are you sure you are removing the old package before installing the new version?

Regarding the location issues: I think pull request #41 solves this. I have just merged this pull request into the master branch. Could you validate that it works?

**Comment by bstienen** [comment]
@mjw63 *poke* O:-)?

**Comment by mjw63** [comment]
Fine now :-)
