### ISSUE TITLE
Allowing external scanners to submit results

### ISSUE THREAD

**Issue by ZacSpec** [DarkMachines/high-dimensional-sampling#9]
With regards to interfacing Pyscannerbit with HDS, given that PS does all the sampling, it will need to give the results to HDS so that Bob's plotting routines work. PS can make available vectors containing all sampled points - is there a way for HDS to treat them like it did the sampling itself and record the results?

**Comment by bstienen** [comment]
So your question is how to get the pyscannerbit results into the HDS package? Results returned by the __call__ method of your Procedure class will automatically get logged correctly. I am not well versed enough in pyscannerbit to know how to do it, nor do I know what your HDS code currently looks like, but if you use __call__’s return to return all stored values within pyscannerbit, I think it should work.
See for example https://github.com/DarkMachines/high-dimensional-sampling/blob/master/examples/random_optimisation.py, where the call method will return 10 datapoints at the same time.
Does this answer your question?

**Comment by ZacSpec** [comment]
Yes it does, thank you.
